//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinOefening
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersoonBadge
    {
        public int PersoonBadgeID { get; set; }
        public Nullable<int> PersoonID { get; set; }
        public Nullable<int> BadgeID { get; set; }
    }
}
